ComicBookLibraryManagerWebApp/Controllers/ComicBookArtistsController.cs
using ComicBookLibraryManagerWebApp.ViewModels;
using ComicBookShared.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ComicBookLibraryManagerWebApp.Controllers
{
    /// <summary>
    /// Controller for adding/deleting comic book artists.
    /// </summary>
    public class ComicBookArtistsController : Controller
    {
        public ActionResult Add(int comicBookId)
        {
            // TODO Get the comic book.
            // Include the "Series" navigation property.
            var comicBook = new ComicBook();

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            var viewModel = new ComicBookArtistsAddViewModel()
            {
                ComicBook = comicBook
            };

            // TODO Pass the Context class to the view model "Init" method.
            viewModel.Init();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(ComicBookArtistsAddViewModel viewModel)
        {
            ValidateComicBookArtist(viewModel);

            if (ModelState.IsValid)
            {
                // TODO Add the comic book artist.

                TempData["Message"] = "Your artist was successfully added!";

                return RedirectToAction("Detail", "ComicBooks", new { id = viewModel.ComicBookId });
            }

            // TODO Prepare the view model for the view.
            // TODO Get the comic book.
            // Include the "Series" navigation property.
            viewModel.ComicBook = new ComicBook();
            // TODO Pass the Context class to the view model "Init" method.
            viewModel.Init();

            return View(viewModel);
        }

        public ActionResult Delete(int comicBookId, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // TODO Get the comic book artist.
            // Include the "ComicBook.Series", "Artist", and "Role" navigation properties.
            var comicBookArtist = new ComicBookArtist();

            if (comicBookArtist == null)
            {
                return HttpNotFound();
            }

            return View(comicBookArtist);
        }

        [HttpPost]
        public ActionResult Delete(int comicBookId, int id)
        {
            // TODO Delete the comic book artist.

            TempData["Message"] = "Your artist was successfully deleted!";

            return RedirectToAction("Detail", "ComicBooks", new { id = comicBookId });
        }

        /// <summary>
        /// Validates a comic book artist on the server
        /// before adding a new record.
        /// </summary>
        /// <param name="viewModel">The view model containing the values to validate.</param>
        private void ValidateComicBookArtist(ComicBookArtistsAddViewModel viewModel)
        {
            //// If there aren't any "ArtistId" and "RoleId" field validation errors...
            //if (ModelState.IsValidField("ArtistId") &&
            //    ModelState.IsValidField("RoleId"))
            //{
            //    // Then make sure that this artist and role combination 
            //    // doesn't already exist for this comic book.
            //    // TODO Call method to check if this artist and role combination
            //    // already exists for this comic book.
            //    if (false)
            //    {
            //        ModelState.AddModelError("ArtistId",
            //            "This artist and role combination already exists for this comic book.");
            //    }
            //}
        }
    }
}

ComicBookLibraryManagerWebApp/Controllers/ComicBooksController.cs
using ComicBookShared.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ComicBookLibraryManagerWebApp.ViewModels;
using System.Net;
using System.Data.Entity.Infrastructure;

namespace ComicBookLibraryManagerWebApp.Controllers
{
    /// <summary>
    /// Controller for the "Comic Books" section of the website.
    /// </summary>
    public class ComicBooksController : Controller
    {
        public ActionResult Index()
        {
            // TODO Get the comic books list.
            // Include the "Series" navigation property.
            var comicBooks = new List<ComicBook>();

            return View(comicBooks);
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // TODO Get the comic book.
            // Include the "Series", "Artists.Artist", and "Artists.Role" navigation properties.
            var comicBook = new ComicBook();

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            // Sort the artists.
            comicBook.Artists = comicBook.Artists.OrderBy(a => a.Role.Name).ToList();

            return View(comicBook);
        }

        public ActionResult Add()
        {
            var viewModel = new ComicBooksAddViewModel();

            // TODO Pass the Context class to the view model "Init" method.
            viewModel.Init();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(ComicBooksAddViewModel viewModel)
        {
            ValidateComicBook(viewModel.ComicBook);

            if (ModelState.IsValid)
            {
                var comicBook = viewModel.ComicBook;
                comicBook.AddArtist(viewModel.ArtistId, viewModel.RoleId);

                // TODO Add the comic book.

                TempData["Message"] = "Your comic book was successfully added!";

                return RedirectToAction("Detail", new { id = comicBook.Id });
            }

            // TODO Pass the Context class to the view model "Init" method.
            viewModel.Init();

            return View(viewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // TODO Get the comic book.
            var comicBook = new ComicBook();

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            var viewModel = new ComicBooksEditViewModel()
            {
                ComicBook = comicBook
            };
            viewModel.Init();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(ComicBooksEditViewModel viewModel)
        {
            ValidateComicBook(viewModel.ComicBook);

            if (ModelState.IsValid)
            {
                var comicBook = viewModel.ComicBook;

                // TODO Update the comic book.

                TempData["Message"] = "Your comic book was successfully updated!";

                return RedirectToAction("Detail", new { id = comicBook.Id });
            }

            viewModel.Init();

            return View(viewModel);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // TODO Get the comic book.
            // Include the "Series" navigation property.
            var comicBook = new ComicBook();

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            return View(comicBook);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            // TODO Delete the comic book.

            TempData["Message"] = "Your comic book was successfully deleted!";

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Validates a comic book on the server
        /// before adding a new record or updating an existing record.
        /// </summary>
        /// <param name="comicBook">The comic book to validate.</param>
        private void ValidateComicBook(ComicBook comicBook)
        {
            //// If there aren't any "SeriesId" and "IssueNumber" field validation errors...
            //if (ModelState.IsValidField("ComicBook.SeriesId") &&
            //    ModelState.IsValidField("ComicBook.IssueNumber"))
            //{
            //    // Then make sure that the provided issue number is unique for the provided series.
            //    // TODO Call method to check if the issue number is available for this comic book.
            //    if (false)
            //    {
            //        ModelState.AddModelError("ComicBook.IssueNumber",
            //            "The provided Issue Number has already been entered for the selected Series.");
            //    }
            //}
        }
    }
}

ComicBookLibraryManagerWebApp/Views/ComicBooks/Add.cshtml
@model ComicBookLibraryManagerWebApp.ViewModels.ComicBooksAddViewModel

@{
    ViewBag.Title = "Add Comic Book";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("The following errors were found:", new { @class = "alert alert-danger" })

    <h3>Main Information</h3>

    @Html.Partial("_ComicBookForm")

    <h3>First Artist</h3>

    <p>Select an artist and role to add to this comic book. 
        Additional artists can be added once the comic book has been saved.</p>

    <div class="row">

        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(m => m.ArtistId, new { @class = "control-label" })
                @Html.DropDownListFor(m => m.ArtistId,
                    Model.ArtistSelectListItems, "", new { @class = "form-control" })
            </div>

        </div>

        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(m => m.RoleId, new { @class = "control-label" })
                @Html.DropDownListFor(m => m.RoleId,
                    Model.RoleSelectListItems, "", new { @class = "form-control" })
            </div>

        </div>

    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="pad-top">
                <button type="submit" class="btn btn-success btn-lg margin-right">
                    <span class="glyphicon glyphicon-save"></span> Save
                </button>
                <a href="@Url.Action("Index")" class="btn btn-warning btn-lg">
                    <span class="glyphicon glyphicon-remove"></span> Cancel
                </a>
            </div>
        </div>
    </div>
}

ComicBookLibraryManagerWebApp/Views/ComicBooks/Delete.cshtml
@model ComicBookShared.Models.ComicBook

@{
    ViewBag.Title = "Delete Comic Book";
}

<h2>@ViewBag.Title</h2>

<div class="alert alert-warning">
    Are you sure you want to delete the comic book @Model.DisplayText?
</div>

@using (Html.BeginForm())
{
    <div class="pad-top">
        <button type="submit" class="btn btn-danger btn-lg margin-right">
            <span class="glyphicon glyphicon-trash"></span> Delete
        </button>
        <a href="@Url.Action("Detail", new { id = Model.Id })" class="btn btn-warning btn-lg">
            <span class="glyphicon glyphicon-remove"></span> Cancel
        </a>
    </div>
}

ComicBookLibraryManagerWebApp/Views/ComicBooks/Detail.cshtml
@model ComicBookShared.Models.ComicBook

@{
    ViewBag.Title = "Comic Book Detail";
}

@Html.Partial("_Message")

<h2>@Model.DisplayText</h2>

<h3>Main Information</h3>

<div class="row">
    <div class="col-md-6">

        <div class="row">
            <div class="col-xs-4 col-sm-4">
                @Html.LabelFor(m => m.SeriesId)
            </div>
            <div class="col-xs-8 col-sm-8">
                @Model.Series.Title
            </div>
        </div>

        <div class="row">
            <div class="col-xs-4 col-sm-4">
                @Html.LabelFor(m => m.IssueNumber)
            </div>
            <div class="col-xs-8 col-sm-8">
                @Model.IssueNumber
            </div>
        </div>

        <div class="row">
            <div class="col-xs-4 col-sm-4">
                @Html.LabelFor(m => m.PublishedOn)
            </div>
            <div class="col-xs-8 col-sm-8">
                @Model.PublishedOn.ToShortDateString()
            </div>
        </div>

        <div class="row">
            <div class="col-xs-4 col-sm-4">
                @Html.LabelFor(m => m.AverageRating)
            </div>
            <div class="col-xs-8 col-sm-8">
                @(Model.AverageRating != null ? Model.AverageRating.Value.ToString("n1") : "N/A")
            </div>
        </div>

    </div>
    <div class="col-md-6">

        <div>
            @Html.LabelFor(m => m.Description)
        </div>
        <div>
            @(!string.IsNullOrWhiteSpace(Model.Description) ? Model.Description : "N/A")
        </div>

    </div>
</div>

<h3>Artists</h3>

<div class="pull-right">
    <a href="@Url.Action("Add", "ComicBookArtists", new { comicbookid = Model.Id })" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span> Add Artist
    </a>
</div>

<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>Role</th>
            <th>Artist</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var artist in Model.Artists)
        {
            <tr>
                <td>@artist.Role.Name</td>
                <td>@artist.Artist.Name</td>
                <td>
                    <div class="pull-right">
                        <a href="@Url.Action("Delete", "ComicBookArtists", new { comicbookid = Model.Id, id = artist.Id })" class="btn btn-danger btn-xs margin-right">
                            <span class="glyphicon glyphicon-trash"></span><span class="hidden-xs"> Delete</span>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="pad-top">
    <a href="@Url.Action("Edit", new { id = Model.Id })" class="btn btn-primary btn-lg margin-right">
        <span class="glyphicon glyphicon-edit"></span> Edit
    </a>
    <a href="@Url.Action("Delete", new { id = Model.Id })" class="btn btn-danger btn-lg margin-right">
        <span class="glyphicon glyphicon-trash"></span> Delete
    </a>
    <a href="@Url.Action("Index")" class="btn btn-default btn-lg">
        <span class="glyphicon glyphicon-step-backward"></span> Back
    </a>
</div>

ComicBookLibraryManagerWebApp/Views/ComicBooks/Edit.cshtml
@model ComicBookLibraryManagerWebApp.ViewModels.ComicBooksEditViewModel

@{
    ViewBag.Title = "Edit Comic Book";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("The following errors were found:", new { @class = "alert alert-danger" })

    <h3>Main Information</h3>

    @Html.Partial("_ComicBookForm")

    <div class="row">
        <div class="col-md-12">
            <div class="pad-top">
                <button type="submit" class="btn btn-success btn-lg margin-right">
                    <span class="glyphicon glyphicon-save"></span> Save
                </button>
                <a href="@Url.Action("Detail", new { id = Model.Id })" class="btn btn-warning btn-lg">
                    <span class="glyphicon glyphicon-remove"></span> Cancel
                </a>
            </div>
        </div>
    </div>
}

ComicBookLibraryManagerWebApp/Views/ComicBooks/Index.cshtml
@model List<ComicBookShared.Models.ComicBook>

@{
    ViewBag.Title = "Comic Books";
}

@Html.Partial("_Message")

<h2>@ViewBag.Title</h2>

<div class="pull-right">
    <a href="@Url.Action("Add")" class="btn btn-primary btn-lg">
        <span class="glyphicon glyphicon-plus"></span> Add Comic Book
    </a>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Comic Book</th>
            <th>Published On</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var comicBook in Model)
        {
            <tr>
                <td>@comicBook.DisplayText</td>
                <td>@comicBook.PublishedOn.ToString("MM/dd/yyyy")</td>
                <td>
                    <div class="pull-right">
                        <a href="@Url.Action("Detail", new { id = comicBook.Id })" class="btn btn-primary btn-xs margin-right">
                            <span class="glyphicon glyphicon-info-sign"></span><span class="hidden-xs"> Detail</span>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

ComicBookLibraryManagerWebApp/Views/ComicBooks/_ComicBookForm.cshtml
@model ComicBookLibraryManagerWebApp.ViewModels.ComicBooksBaseViewModel

<div class="row">

    <div class="col-md-6">

        <div class="form-group">
            @Html.LabelFor(m => m.ComicBook.SeriesId, new { @class = "control-label" })
            @Html.DropDownListFor(m => m.ComicBook.SeriesId,
            Model.SeriesSelectListItems, "", new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ComicBook.IssueNumber, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.ComicBook.IssueNumber, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ComicBook.PublishedOn, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.ComicBook.PublishedOn, "{0:d}", new { @class = "form-control datepicker" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ComicBook.AverageRating, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.ComicBook.AverageRating, "{0:n1}", new { @class = "form-control" })
        </div>

    </div>

    <div class="col-md-6">

        <div class="form-group">
            @Html.LabelFor(m => m.ComicBook.Description, new { @class = "control-label" })
            @Html.TextAreaFor(m => m.ComicBook.Description, 14, 20, new { @class = "form-control" })
        </div>

    </div>

</div>